# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 21:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('histoslide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerNumeric', models.IntegerField(default=0)),
                ('AnswerText', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Order', models.IntegerField(default=0)),
                ('Introduction', models.TextField()),
                ('Report', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['Order', 'Name'],
            },
        ),
        migrations.CreateModel(
            name='CaseBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=50)),
                ('CenterX', models.FloatField(default=0.0)),
                ('CenterY', models.FloatField(default=0.0)),
                ('Zoom', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Case')),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histoslide.Slide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[(b'O', b'Open'), (b'S', b'Skipped'), (b'E', b'Ended')], max_length=1)),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('EndTime', models.DateTimeField(auto_now=True)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Case')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Abstract', models.TextField()),
                ('Description', models.TextField()),
                ('InviteMail', models.TextField()),
                ('WelcomeMail', models.TextField()),
                ('ReminderMail', models.TextField()),
                ('Type', models.CharField(choices=[(b'O', b'Observer variability'), (b'C', b'Case reporting'), (b'E', b'Examination')], max_length=1)),
                ('ObserversPerCase', models.PositiveIntegerField(default=0, help_text=b'Enter 0 to have all cases seen by observers')),
                ('VisibleForNonUsers', models.BooleanField(default=False, help_text=b'Case shows up on main screen when a user is not assigned to this case list')),
                ('OpenForRegistration', models.BooleanField(default=False, help_text=b'A user can admit himself to this case list')),
                ('SelfRegistration', models.BooleanField(default=False, help_text=b'If false, the owner must accept the admittance of a user to the case list')),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=10)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseListInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caselist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.CaseList')),
                ('Invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation.InvitationKey')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Case')),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histoslide.Slide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[(b'M', b'MultipleChoice'), (b'O', b'Open text'), (b'N', b'Numeric'), (b'D', b'Date'), (b'R', b'Remark')], max_length=1)),
                ('Order', models.IntegerField()),
                ('Text', models.CharField(max_length=200)),
                ('Required', models.BooleanField(default=False)),
                ('CorrectAnswer', models.CharField(blank=True, max_length=40)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Case')),
            ],
            options={
                'ordering': ['Order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField()),
                ('Text', models.CharField(max_length=200)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Question')),
            ],
            options={
                'ordering': ['Order'],
            },
        ),
        migrations.CreateModel(
            name='UserCaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[(b'A', b'Active'), (b'P', b'Pending'), (b'C', b'Complete')], default=b'A', max_length=1)),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('CaseList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.CaseList')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caselist',
            name='Users',
            field=models.ManyToManyField(through='rateslide.UserCaseList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='Caselist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.CaseList'),
        ),
        migrations.AddField(
            model_name='case',
            name='Slides',
            field=models.ManyToManyField(through='rateslide.CaseSlide', to='histoslide.Slide'),
        ),
        migrations.AddField(
            model_name='answer',
            name='CaseInstance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.CaseInstance'),
        ),
        migrations.AddField(
            model_name='answer',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Question'),
        ),
    ]
