# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateslide', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseinstance',
            name='Status',
            field=models.CharField(choices=[('O', 'Open'), ('S', 'Skipped'), ('E', 'Ended')], max_length=1),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='ObserversPerCase',
            field=models.PositiveIntegerField(default=0, help_text='Enter 0 to have all cases seen by observers'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='OpenForRegistration',
            field=models.BooleanField(default=False, help_text='A user can admit himself to this case list'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='SelfRegistration',
            field=models.BooleanField(default=False, help_text='If false, the owner must accept the admittance of a user to the case list'),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='Type',
            field=models.CharField(choices=[('O', 'Observer variability'), ('C', 'Case reporting'), ('E', 'Examination'), ('S', 'Show case')], max_length=1),
        ),
        migrations.AlterField(
            model_name='caselist',
            name='VisibleForNonUsers',
            field=models.BooleanField(default=False, help_text='Case shows up on main screen when a user is not assigned to this case list'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Type',
            field=models.CharField(choices=[('M', 'MultipleChoice'), ('O', 'Open text'), ('N', 'Numeric'), ('D', 'Date'), ('R', 'Remark')], max_length=1),
        ),
        migrations.AlterField(
            model_name='usercaselist',
            name='Status',
            field=models.CharField(choices=[('A', 'Active'), ('P', 'Pending'), ('C', 'Complete')], default='A', max_length=1),
        ),
    ]
