# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 15:06
from __future__ import unicode_literals

import django_extensions.db.fields
from django.db import migrations
from rateslide.models import CaseList

def migrate_data_forward(apps, schema_editor):
    for instance in CaseList.objects.all():
        print("Generating slug for %s" % instance)
        instance.save() # Will trigger slug update

def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('rateslide', '0002_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='Slug',
            field=django_extensions.db.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='Name', unique=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
