# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0003_slide_ordering'),
        ('rateslide', '0004_caselist_slug_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=50)),
                ('CenterX', models.FloatField(default=0.0)),
                ('CenterY', models.FloatField(default=0.0)),
                ('Zoom', models.FloatField(default=1.0)),
                ('order', models.IntegerField(default=0)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Question')),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histoslide.Slide')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
