# Generated by Django 2.0.2 on 2018-02-25 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateslide', '0005_questionbookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselist',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
