# Generated by Django 2.0.2 on 2018-04-22 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('histoslide', '0003_slide_ordering'),
        ('rateslide', '0006_protect_caselist_from_deleting_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnotationJSON', models.TextField()),
                ('Length', models.FloatField()),
                ('LengthUnit', models.CharField(blank=True, max_length=10)),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='histoslide.Slide')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rateslide.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='Type',
            field=models.CharField(choices=[('M', 'MultipleChoice'), ('O', 'Open text'), ('N', 'Numeric'), ('D', 'Date'), ('R', 'Remark'), ('L', 'Line')], max_length=1),
        ),
    ]
